# Generated by Django 5.2 on 2025-04-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='тема заметки')),
                ('body', models.TextField(verbose_name='заметка')),
            ],
            options={
                'verbose_name': 'заметка',
                'verbose_name_plural': 'заметки',
                'ordering': ['title'],
                'permissions': [('can_unpublish_note', 'Can unpublish note'), ('can_delete_note', 'Can delete note'), ('view_all_note', 'View all notes'), ('can_create_note', 'Can create a note'), ('can_edit_note', 'Can edit a note')],
            },
        ),
    ]
